/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author koke
 */
public class PrincipalFrom extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalFrom
     */
    public PrincipalFrom() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miGenerarVenta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        imProductos = new javax.swing.JMenuItem();
        imVendedores = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        imReportes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        jMenu1.setText("Menu");

        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        jMenu1.add(miSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoventas.png"))); // NOI18N
        jMenu2.setText("Ventas");

        miGenerarVenta.setText("GenerarVenta");
        miGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGenerarVentaActionPerformed(evt);
            }
        });
        jMenu2.add(miGenerarVenta);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logomanten.png"))); // NOI18N
        jMenu3.setText("Almacén");

        imProductos.setText("Productos");
        imProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imProductosActionPerformed(evt);
            }
        });
        jMenu3.add(imProductos);

        imVendedores.setText("Vendedores");
        imVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imVendedoresActionPerformed(evt);
            }
        });
        jMenu3.add(imVendedores);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportes.png"))); // NOI18N
        jMenu4.setText("Reportes");

        imReportes.setText("Reportes");
        imReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imReportesActionPerformed(evt);
            }
        });
        jMenu4.add(imReportes);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "¿Desea salir?", "Advertencia", dialogButton);
        
        if (dialogResult == 0) {
            System.exit(0);
        }
        else
        {
            
        }
    }//GEN-LAST:event_miSalirActionPerformed

    private void miGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGenerarVentaActionPerformed
        // TODO add your handling code here:
        VentasForm vf = new VentasForm();
        centrarVentana(vf);
    }//GEN-LAST:event_miGenerarVentaActionPerformed

    private void imProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imProductosActionPerformed
        // TODO add your handling code here:
        ProductoForm pf = new ProductoForm();
        centrarVentana(pf);
    }//GEN-LAST:event_imProductosActionPerformed

    private void imVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imVendedoresActionPerformed
        // TODO add your handling code here:
        VendedorForm venf = new VendedorForm();
        centrarVentana(venf);
    }//GEN-LAST:event_imVendedoresActionPerformed

    private void imReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imReportesActionPerformed
        // TODO add your handling code here:
        ReportesForm rf = new ReportesForm();
        centrarVentana(rf);
    }//GEN-LAST:event_imReportesActionPerformed

    void centrarVentana(JInternalFrame freme){
        ventanaPrincipal.add(freme);
        Dimension dimension = ventanaPrincipal.getSize();
        Dimension Dfreme = freme.getSize();
        freme.setLocation((dimension.width - Dfreme.width)/2, (dimension.height - Dfreme.height)/2);
        freme.show();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem imProductos;
    private javax.swing.JMenuItem imReportes;
    private javax.swing.JMenuItem imVendedores;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miGenerarVenta;
    private javax.swing.JMenuItem miSalir;
    public static javax.swing.JDesktopPane ventanaPrincipal;
    // End of variables declaration//GEN-END:variables
}
